# Linear Regression
### We are interested in how changes in these variables affect future temperatures, as well as how well these variables explain temperature changes so far. To do this, first read the dataset GlobalWarming.csv into R/Python.

In [13]:
import pandas as pd
import numpy as np

In [35]:
data=pd.read_csv("GlobalWarming.csv")

In [36]:
data.head(5)

,Year,Month,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
0,1983,5,2.556,345.96,1638.59,303.677,191.324,350.113,1366.1024,0.0863,0.109
1,1983,6,2.167,345.52,1633.71,303.746,192.057,351.848,1366.1208,0.0794,0.118
2,1983,7,1.741,344.15,1633.22,303.795,192.818,353.725,1366.2850,0.0731,0.137
3,1983,8,1.130,342.25,1631.35,303.839,193.602,355.633,1366.4202,0.0673,0.176
4,1983,9,0.428,340.17,1648.40,303.901,194.392,357.465,1366.2335,0.0619,0.149

In [37]:
data.drop(data.columns[0:2], axis = 1 )

,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
0,2.556,345.96,1638.59,303.677,191.324,350.113,1366.1024,0.0863,0.109
1,2.167,345.52,1633.71,303.746,192.057,351.848,1366.1208,0.0794,0.118
2,1.741,344.15,1633.22,303.795,192.818,353.725,1366.2850,0.0731,0.137
3,1.130,342.25,1631.35,303.839,193.602,355.633,1366.4202,0.0673,0.176
4,0.428,340.17,1648.40,303.901,194.392,357.465,1366.2335,0.0619,0.149
5,0.002,340.30,1663.79,303.970,195.171,359.174,1366.0589,0.0569,0.093
6,-0.176,341.53,1658.23,304.032,195.921,360.758,1366.1072,0.0524,0.232
7,-0.176,343.07,1654.31,304.082,196.609,362.174,1366.0607,0.0486,0.078
8,-0.339,344.05,1658.98,304.130,197.219,363.359,1365.4261,0.0451,0.089
9,-0.565,344.77,1656.48,304.194,197.759,364.296,1365.6618,0.0416,0.013
10,0.131,345.46,1655.77,304.285,198.249,365.044,1366.1697,0.0383,0.049
11,0.331,346.77,1657.68,304.389,198.723,365.692,1365.5660,0.0352,-0.019
12,0.121,347.55,1649.33,304.489,199.233,366.317,1365.7783,0.0324,0.065
13,-0.142,346.98,1634.13,304.593,199.858,367.029,1366.0956,0.0302,-0.016
14,-0.138,345.55,1629.89,304.722,200.671,367.893,1366.1145,0.0282,-0.024
15,-0.179,343.20,1643.67,304.871,201.710,368.843,1365.9781,0.0260,0.034
16,-0.082,341.35,1663.60,305.021,202.972,369.800,1365.8669,0.0239,0.025
17,0.016,341.68,1674.65,305.158,204.407,370.782,1365.7869,0.0220,-0.035
18,-0.351,343.06,1677.10,305.263,205.893,371.770,1365.6802,0.0202,-0.123
19,-0.611,344.54,1672.15,305.313,207.308,372.701,1365.7617,0.0188,-0.282
20,-0.561,345.25,1663.42,305.301,208.537,373.623,1365.6082,0.0164,-0.001
21,-0.602,346.06,1666.21,305.243,209.543,374.681,1365.7085,0.0160,-0.155
22,-0.737,347.66,1678.34,305.165,210.368,376.004,1365.6570,0.0141,-0.032
23,-0.484,348.20,1675.24,305.093,211.111,377.635,1365.5120,0.0138,-0.042
24,-0.731,348.92,1666.83,305.045,211.823,379.539,1365.6366,0.0128,0.001
25,-0.086,348.40,1659.40,305.027,212.512,381.642,1365.6964,0.0126,-0.049
26,-0.156,346.66,1654.25,305.049,213.165,383.905,1365.6509,0.0121,-0.042
27,-0.392,344.85,1654.41,305.126,213.803,386.223,1365.7499,0.0116,0.013
28,-0.541,343.20,1668.31,305.250,214.501,388.500,1365.6653,0.0102,-0.035
29,-0.140,343.08,1681.56,305.395,215.327,390.676,1365.5269,0.0101,-0.008
...,...,...,...,...,...,...,...,...,...
278,0.628,382.38,1765.95,319.872,249.247,539.725,1365.8212,0.0038,0.456
279,0.759,380.45,1762.66,319.930,248.981,539.682,1365.7067,0.0041,0.482
280,0.793,378.92,1776.04,320.010,248.775,539.566,1365.8419,0.0043,0.425
281,0.892,379.16,1789.02,320.125,248.666,539.488,1365.8270,0.0044,0.472
282,1.292,380.18,1791.91,320.321,248.605,539.500,1365.7039,0.0049,0.440
283,0.951,381.79,1795.04,320.451,248.480,539.377,1365.7087,0.0054,0.518
284,0.974,382.93,1799.66,320.561,248.372,539.206,1365.7173,0.0054,0.601
285,0.510,383.81,1803.08,320.571,248.264,538.973,1365.7145,0.0051,0.498
286,0.074,384.56,1803.10,320.548,247.997,538.811,1365.7544,0.0045,0.435
287,-0.049,386.40,1802.11,320.518,247.574,538.586,1365.7228,0.0045,0.466
288,0.183,386.58,1795.65,320.445,247.224,538.130,1365.6932,0.0041,0.372
289,-0.358,386.05,1781.81,320.332,246.881,537.376,1365.7616,0.0040,0.382
290,-0.290,384.49,1771.89,320.349,246.497,537.113,1365.7506,0.0040,0.394
291,-0.440,382.00,1779.38,320.471,246.307,537.125,1365.7566,0.0041,0.358
292,-1.162,380.90,1794.21,320.618,246.214,537.281,1365.7159,0.0042,0.402
293,-1.142,381.14,1802.38,320.855,246.189,537.380,1365.7388,0.0041,0.362
294,-1.177,382.42,1803.79,321.062,246.178,537.319,1365.6680,0.0042,0.266
295,-1.168,383.89,1805.58,321.217,246.261,537.052,1365.6927,0.0040,0.226
296,-1.011,385.44,1809.92,321.328,246.183,536.876,1365.7163,0.0038,0.074
297,-1.402,385.73,1803.45,321.345,245.898,536.484,1365.7366,0.0036,0.198
298,-1.635,385.97,1792.84,321.295,245.430,535.979,1365.6726,0.0034,0.447
299,-0.942,387.16,1792.57,321.354,245.086,535.648,1365.7146,0.0033,0.278
300,-0.355,388.50,1796.43,321.420,244.914,535.399,1365.7175,0.0031,0.283
301,0.128,387.88,1791.80,321.447,244.676,535.128,1365.6730,0.0031,0.315
302,0.003,386.42,1782.93,321.372,244.434,535.026,1365.6720,0.0033,0.406
303,-0.266,384.15,1779.88,321.405,244.200,535.072,1365.6570,0.0036,0.407
304,-0.643,383.09,1795.08,321.529,244.083,535.048,1365.6647,0.0043,0.378
305,-0.780,382.99,1814.18,321.796,244.080,534.927,1365.6759,0.0046,0.440
306,-0.621,384.13,1812.37,322.013,244.225,534.906,1365.7065,0.0048,0.394
307,-0.666,385.56,1812.88,322.182,244.204,535.005,1365.6926,0.0046,0.330

In [38]:
data.head(5)

,Year,Month,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
0,1983,5,2.556,345.96,1638.59,303.677,191.324,350.113,1366.1024,0.0863,0.109
1,1983,6,2.167,345.52,1633.71,303.746,192.057,351.848,1366.1208,0.0794,0.118
2,1983,7,1.741,344.15,1633.22,303.795,192.818,353.725,1366.2850,0.0731,0.137
3,1983,8,1.130,342.25,1631.35,303.839,193.602,355.633,1366.4202,0.0673,0.176
4,1983,9,0.428,340.17,1648.40,303.901,194.392,357.465,1366.2335,0.0619,0.149

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 11 columns):
Year        308 non-null int64
Month       308 non-null int64
MEI         308 non-null float64
CO2         308 non-null float64
CH4         308 non-null float64
N2O         308 non-null float64
CFC-11      308 non-null float64
CFC-12      308 non-null float64
TSI         308 non-null float64
Aerosols    308 non-null float64
Temp        308 non-null float64
dtypes: float64(9), int64(2)
memory usage: 26.5 KB

In [40]:
data.describe()

,Year,Month,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
count,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000,308.000000
mean,1995.662338,6.551948,0.275555,363.226753,1749.824513,312.391834,251.973068,497.524782,1366.070759,0.016657,0.256776
std,7.423197,3.447214,0.937918,12.647125,46.051678,5.225131,20.231783,57.826899,0.399610,0.029050,0.179090
min,1983.000000,1.000000,-1.635000,340.170000,1629.890000,303.677000,191.324000,350.113000,1365.426100,0.001600,-0.282000
25%,1989.000000,4.000000,-0.398750,353.020000,1722.182500,308.111500,246.295500,472.410750,1365.717050,0.002800,0.121750
50%,1996.000000,7.000000,0.237500,361.735000,1764.040000,311.507000,258.344000,528.356000,1365.980900,0.005750,0.248000
75%,2002.000000,10.000000,0.830500,373.455000,1786.885000,316.979000,267.031000,540.524250,1366.363250,0.012600,0.407250
max,2008.000000,12.000000,3.001000,388.500000,1814.180000,322.182000,271.494000,543.813000,1367.316200,0.149400,0.739000

In [41]:
data.isnull().values.any()

False

In [42]:
data.corr()

,Year,Month,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
Year,1.000000,-0.025789,-0.145345,0.985379,0.910563,0.994850,0.460965,0.870067,0.022353,-0.361884,0.755731
Month,-0.025789,1.000000,-0.016345,-0.096287,0.017558,0.012395,-0.014914,-0.001084,-0.032754,0.014845,-0.098016
MEI,-0.145345,-0.016345,1.000000,-0.152911,-0.105555,-0.162375,0.088171,-0.039836,-0.076826,0.352351,0.135292
CO2,0.985379,-0.096287,-0.152911,1.000000,0.872253,0.981135,0.401284,0.823210,0.017867,-0.369265,0.748505
CH4,0.910563,0.017558,-0.105555,0.872253,1.000000,0.894409,0.713504,0.958237,0.146335,-0.290381,0.699697
N2O,0.994850,0.012395,-0.162375,0.981135,0.894409,1.000000,0.412155,0.839295,0.039892,-0.353499,0.743242
CFC-11,0.460965,-0.014914,0.088171,0.401284,0.713504,0.412155,1.000000,0.831381,0.284629,-0.032302,0.380111
CFC-12,0.870067,-0.001084,-0.039836,0.823210,0.958237,0.839295,0.831381,1.000000,0.189270,-0.243785,0.688944
TSI,0.022353,-0.032754,-0.076826,0.017867,0.146335,0.039892,0.284629,0.189270,1.000000,0.083238,0.182186
Aerosols,-0.361884,0.014845,0.352351,-0.369265,-0.290381,-0.353499,-0.032302,-0.243785,0.083238,1.000000,-0.392069
Temp,0.755731,-0.098016,0.135292,0.748505,0.699697,0.743242,0.380111,0.688944,0.182186,-0.392069,1.000000

### 1. Find the correlations between all the variables in the dataset except Date & Month. Which of the following independent variables is N2O highly correlated with (absolute correlation greater than 0.7)?

### Ans: 

#### N20 has very high correlation with CO2,CH4 and CFC-12

In [43]:
data.columns

Index(['Year', 'Month', 'MEI', 'CO2', 'CH4', 'N2O', 'CFC-11', 'CFC-12', 'TSI',
       'Aerosols', 'Temp'],
      dtype='object')

In [83]:
data_mat = data[["MEI", "CO2", "CH4", "N2O", "CFC-11", "CFC-12", "TSI","Aerosols"]].values
data_mat

array([[  2.55600000e+00,   3.45960000e+02,   1.63859000e+03, ...,
          3.50113000e+02,   1.36610240e+03,   8.63000000e-02],
       [  2.16700000e+00,   3.45520000e+02,   1.63371000e+03, ...,
          3.51848000e+02,   1.36612080e+03,   7.94000000e-02],
       [  1.74100000e+00,   3.44150000e+02,   1.63322000e+03, ...,
          3.53725000e+02,   1.36628500e+03,   7.31000000e-02],
       ...,
       [ -7.80000000e-01,   3.82990000e+02,   1.81418000e+03, ...,
          5.34927000e+02,   1.36567590e+03,   4.60000000e-03],
       [ -6.21000000e-01,   3.84130000e+02,   1.81237000e+03, ...,
          5.34906000e+02,   1.36570650e+03,   4.80000000e-03],
       [ -6.66000000e-01,   3.85560000e+02,   1.81288000e+03, ...,
          5.35005000e+02,   1.36569260e+03,   4.60000000e-03]])

In [59]:
data_mat.shape

(308, 8)

In [60]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [84]:
vif = [ variance_inflation_factor( data_mat, i ) for i in range( data_mat.shape[1] ) ]

In [85]:
vif_factors = pd.DataFrame()

In [86]:
vif_factors['column'] = ["MEI", "CO2", "CH4", "N2O", "CFC-11", "CFC-12", "TSI","Aerosols"]

In [87]:
vif_factors['vif'] = vif

In [88]:
vif_factors

     column            vif
0       MEI       1.294692
1       CO2   23119.661557
2       CH4   27704.707751
3       N2O  218504.477128
4    CFC-11    4978.537930
5    CFC-12    6953.152798
6       TSI  126014.977486
7  Aerosols       1.778039

### 2. What is Multicollinearity? Does Multicollinearity exist in this Data?

### Ans: 

#### Multicollinearity is a statistical phenomenon in which multiple independent variables show high correlation between each other. This correlation is a problem because independent variables should be independent

#### Yes, there is multicollinearity between few independent variables

In [66]:
data.corr()

,Year,Month,MEI,CO2,CH4,N2O,CFC-11,CFC-12,TSI,Aerosols,Temp
Year,1.000000,-0.025789,-0.145345,0.985379,0.910563,0.994850,0.460965,0.870067,0.022353,-0.361884,0.755731
Month,-0.025789,1.000000,-0.016345,-0.096287,0.017558,0.012395,-0.014914,-0.001084,-0.032754,0.014845,-0.098016
MEI,-0.145345,-0.016345,1.000000,-0.152911,-0.105555,-0.162375,0.088171,-0.039836,-0.076826,0.352351,0.135292
CO2,0.985379,-0.096287,-0.152911,1.000000,0.872253,0.981135,0.401284,0.823210,0.017867,-0.369265,0.748505
CH4,0.910563,0.017558,-0.105555,0.872253,1.000000,0.894409,0.713504,0.958237,0.146335,-0.290381,0.699697
N2O,0.994850,0.012395,-0.162375,0.981135,0.894409,1.000000,0.412155,0.839295,0.039892,-0.353499,0.743242
CFC-11,0.460965,-0.014914,0.088171,0.401284,0.713504,0.412155,1.000000,0.831381,0.284629,-0.032302,0.380111
CFC-12,0.870067,-0.001084,-0.039836,0.823210,0.958237,0.839295,0.831381,1.000000,0.189270,-0.243785,0.688944
TSI,0.022353,-0.032754,-0.076826,0.017867,0.146335,0.039892,0.284629,0.189270,1.000000,0.083238,0.182186
Aerosols,-0.361884,0.014845,0.352351,-0.369265,-0.290381,-0.353499,-0.032302,-0.243785,0.083238,1.000000,-0.392069
Temp,0.755731,-0.098016,0.135292,0.748505,0.699697,0.743242,0.380111,0.688944,0.182186,-0.392069,1.000000

### 3. Which variables are highly correlated with the Dependent Variable? Is Co-relation god or bad for the Model? Why?

### Ans: 

#### CO2,CH4,N20 and CFC-12 has very high correlation with dependent variable Temperatue and correlation bwteen dependent and independent variable is good, but it also hints about multicoliniority between the dependent variables, which will definetly effect the model performance.

### 4. What will be the prediction of a baseline Model? What will be its SSE, more commonly known as SST/TSS?

### Ans: 
#### Baseline prediction is nothing but the average value of dependent variable

In [67]:
baseline_model=data.Temp.mean()

In [68]:
baseline_model

0.256775974025974

###  SST (total sum of squares) = SSE(error sum of squares) + SSR (regression sum of squares)

In [69]:
SST=sum((data.Temp-baseline_model)**2)

In [70]:
SST

9.8464555422077886

### 5. Build a linear regression model to predict the dependent variable Temp, using CO2, N2O, CFC.12, and Aerosols as independent variables. 

### Find the RMSE, SSE and MAPE for the above Model. What is the model R2 (the "Multiple R-squared" value & Adjusted R2).

In [71]:
import statsmodels.api as sm

C:\Users\nagapavan\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [72]:
x=sm.add_constant(data[["CO2", "N2O", "CFC-12", "Aerosols" ]])

In [73]:
y=data.Temp

In [74]:
lm = sm.OLS( y, x ).fit()

In [89]:
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                   Temp   R-squared:                       0.596
Model:                            OLS   Adj. R-squared:                  0.591
Method:                 Least Squares   F-statistic:                     111.9
Date:                Wed, 22 Aug 2018   Prob (F-statistic):           1.81e-58
Time:                        23:44:55   Log-Likelihood:                 232.93
No. Observations:                 308   AIC:                            -455.9
Df Residuals:                     303   BIC:                            -437.2
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -2.9781      1.198     -2.485      0.013      -5.336      -0.620
CO2            0.0060      0.003      2.242      0.026       0.001       0.011
N2O            0.0022      0.007      0.320      0.749      -0.011       0.015
CFC-12         0.0008      0.000      3.673      0.000       0.000       0.001
Aerosols      -0.9362      0.244     -3.841      0.000      -1.416      -0.457
==============================================================================
Omnibus:                        5.792   Durbin-Watson:                   0.555
Prob(Omnibus):                  0.055   Jarque-Bera (JB):                6.779
Skew:                           0.181   Prob(JB):                       0.0337
Kurtosis:                       3.630   Cond. No.                     1.27e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.27e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

### R_square=0.596
### Adjusted_R_square=0.591

In [76]:
lmpredict = lm.predict(x)

In [77]:
lmpredict[0:4]

0   -0.044721
1   -0.039437
2   -0.040265
3   -0.044750
dtype: float64

In [78]:
from statsmodels.tools.eval_measures import rmse

In [79]:
rmse( y, lmpredict )

0.11358646701873874

In [91]:
SSE=sum((y-lmpredict)**2)

In [94]:
3**2

9

In [108]:
SSE

3.9737807308580972

In [ ]:
def mape_vectorized_v2(a, b): 
    mask = a != 0
    return (np.fabs(a - b)/a)[mask].mean()  ## one more way to find MAPE

In [112]:
def mean_absolute_percentage_error(y_true, y_pred): 
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

In [113]:
mean_absolute_percentage_error(y, lmpredict)

159.49003764897495

### 6. Calculate R2 value manually using the formulae for R2. Both should match.

### R_Square= SSR/SST

###  SST (total sum of squares) = SSE(error sum of squares) + SSR (regression sum of squares)

In [114]:
SSE=sum((y-lmpredict)**2)

In [115]:
avg_of_predication=lmpredict.mean()

In [97]:
SSR=sum((lmpredict-baseline_model)**2)

In [98]:
SST=SSR+SSE

In [99]:
R_Square=SSR/SST

In [100]:
R_Square

0.59642526045802957

### 7. Find the correlation between the actual & predicted values of Temp. Square this number and you should get the Multiple R2. This is another quick way to compute R2. ( R2= correlation(actual, predicted values)^2)

In [95]:
correlation=lmpredict.corr(y)

In [96]:
correlation**2

0.5964252604580299

### 8. What is the Hypothesis test in case of a Linear Regression?

### Ans:

#### Null Hypothesis: There is no significant linear relationship between the independent variable x and the dependent variable y (B1=B2=B3....=0)

#### Alternative Hypothesis: There is a no significant linear relationship between the independent variable x and the dependent variable y (B1 !=0). Atleast one variable is significant.

### 9. What do the P values represent? Do we look for low or High P values? Why?

### Ans:

#### A p value is used in hypothesis testing to help you support or reject the null hypothesis. The p value is the evidence against a null hypothesis. 
#### The smaller the p-value, the strong the evidence that you should reject the null hypothesis, so we normally look for smaller p-value.

### 10. What is an F Test in Linear Regression? Discuss.

### Ans:

#### The F-test of overall significance indicates whether the  linear regression model provides a better fit to the data than a model that contains no independent variables. 

#### In general, an F-test in regression compares the fits of different linear models. Unlike t-tests that can assess only one regression coefficient at a time, the F-test can assess multiple coefficients simultaneously.

#### If the P value for the F-test of overall significance test is less than your significance level, we can reject the null-hypothesis and conclude that your model provides a better fit than the intercept-only model.

# ---The End---